endpoints:
  apiTheMovieDb:
    token: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiODE5NDM4NzJhZDhkNWRlMzgwODlmMjYwMWQ4MWI3ZCIsInN1YiI6IjYxMGNiOTU3ZTc4Njg3MDA1ZTkyZjYzZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.gdu9M6yingzaVUKEwKnBST8YDxswRDAmJDB1NZ36xSc'
    searchMovie: 'https://api.themoviedb.org/3/search/movie'

spring:
  datasource:
    url: jdbc:h2:mem:catalogo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

messages:
  movieDeleted:
    message: "Película eliminada con éxito"
errors:
  errorMovieExist:
    code: E001
    message: "Error, Uno o mas datos de esta película ya existe en nuestros registros"
  errorUpdateMovie:
    code: E002
    message: "Error, no se puede actualizar este registro, el identificador ya no existe"
  errorMovieUuidNotFound:
    code: E003
    message: "Error, este registro ya no existe"
  errorDeleteMovieUuidNotFound:
    code: E003
    message: "Error, no se puede eliminar el registro, el identificador ya no existe"

