spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/cepardov/config-server-files}
          refreshRate: 30
          default-label: ${CONFIG_GIT_LABEL:master}
server:
  port: 8888